//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empregado
    {
        public int id_empregado { get; set; }
        public string nome { get; set; }
        public Nullable<int> matrícula { get; set; }
        public Nullable<int> cpf { get; set; }
        public string endereço { get; set; }
        public int id_dependente { get; set; }
    
        public virtual Dependente Dependente { get; set; }
    }
}
